[workspace]
members = [
    "fvm",
    "sdk",
    "shared",
    "actors/*",
    "cgo/rust",
    "examples/actor",
    "examples/blockstore-cgo/user",
    "testing/conformance",
    "ipld/*",
]
exclude = [
    "examples/blockstore-cgo"
]

default-members = [
    "fvm",
    "sdk",
    "shared",
    "actors/*",
    "testing/conformance",
    "ipld/*"
    # don't build the examples by default, as they require a specific target and profile.
    # build them with cargo make examples
    # "examples/*"
]

[patch.crates-io]
multihash = { git = "https://github.com/multiformats/rust-multihash", branch = "next" }
cid = { git = "https://github.com/multiformats/rust-cid", branch = "cid-as-newtype-struct" }
ipld_hamt = { path = "./ipld/hamt" }
ipld_amt = { path = "./ipld/amt" }
fvm_shared = { path = "./shared" }
forest_bitfield = { path = "./ipld/bitfield" }
filecoin-proofs-api = { git = "https://github.com/filecoin-project/rust-filecoin-proofs-api" }
filecoin-proofs = { git = "https://github.com/filecoin-project/rust-fil-proofs" }
storage-proofs-porep = { git = "https://github.com/filecoin-project/rust-fil-proofs" }
sha2raw = { git = "https://github.com/filecoin-project/rust-fil-proofs" }
fr32 = { git = "https://github.com/filecoin-project/rust-fil-proofs" }

[profile.actor]
inherits = "release"
panic = "abort"
overflow-checks = true
lto = true
opt-level = "z"
#strip = true
