[package]
name = "forest_bitfield"
description = "Bitfield logic for use in Filecoin actors"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2018"
repository = "https://github.com/ChainSafe/forest"

[dependencies]
unsigned-varint = "0.7.1"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = { package = "cs_serde_bytes", version = "0.12" }
fvm_shared = { version = "0.1.0", path = "../../shared" }

[dev-dependencies]
rand_xorshift = "0.2.0"
rand = "0.7.3"
criterion = "0.3"
serde_json = "1.0"

[features]
json = []

[[bench]]
name = "benchmarks"
harness = false
